version: "2"         # required to adjust maintainability checks

engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
  reek:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "**.rb"